export const FETCH_AUTH_ID = "FETCH_AUTH_ID";
export const REMOVE_AUTH_ID = "REMOVE_AUTH_ID";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const FETCH_BOTTOM_TAB_HEIGHT = "FETCH_BOTTOM_TAB_HEIGHT";

export const FETCH_FAVOURITE_RESTAURANTS = "FETCH_FAVOURITE_RESTAURANTS";
export const REMOVE_FAVOURITE_RESTAURANTS = "REMOVE_FAVOURITE_RESTAURANTS";
